### ISSUE TITLE
problem with installing SAFBuilder on windows

### ISSUE THREAD

**Issue by lbkitko** [DSpace-Labs/SAFBuilder#17]
Hello, I follow the instruction on installing SAFBuilder on windows, but run into problem.  There is no recompile.bat in the folder. Please assist. Thanks.

**Comment by asimmsrao** [comment]
How did you solved it?

**Comment by lbkitko** [comment]
Have to use Git to install the package
Download and install Git
https://git-scm.com/download/win

**Comment by asimmsrao** [comment]
Got it. It's working now. Thank you 😊.
